# for prod profile use mysql database over in-memory H2
spring:
 # When can unconditionally include other profiles as well, below property will include proddb profile when prod profile is active, here results are actually same
  profiles:
    include: 
      - proddb
# Disable h2-console for prod  
  h2:
    console:
      enabled: false   
      
# change log level to error for prod profile, NOTE: Since we are not overriding file name, file name property will be used from properties.yml
logging:
  level:
    root: error
    liquibase.executor: error
  
# disable all other actuator endpoints and allow only loggers, so that we can change logs level at runtime.
management:
  endpoints:
    web:
      exposure:
         include: "loggers"
         
acme:
  enabled: false
  remote-address: 192.168.122
  security:
    username: amipatil
    password: asdf1245
    # arrays/list can be comma separated as -> roles: USER,ADMIN
    roles:
      - USER
      - ADMIN
      - SPITTLE